#!/usr/bin/env python3
import sys

with open(sys.argv[1]) as handle:
    cell_line = sys.argv[1].split('/')[-3].split('_')[1]
    for line in handle.readlines():
        if not line[0] == '#':
            lst = line.strip().split(',')

            if lst[2] == 'stable':
                print(cell_line + ',' + str(float(lst[5])*2))